version: 2

jobs:
  build:
    working_directory: ~/core.typed.annotator.jvm
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.9.0.397.sh
            chmod +x linux-install-1.9.0.397.sh
            sudo ./linux-install-1.9.0.397.sh
      - run: ./script/test
        #- run: mvn --version
        #- run: mvn test
        #- run: mvn install -DskipTests=true
        #- run:
        #    command: |
        #      git clone https://github.com/frenchy64/runtime-type-inference-lein.git ~/runtime-type-inference-lein
        #- run:
        #    command: |
        #      cd ~/runtime-type-inference-lein
        #      ./infer-types.sh
